src/rasterstats/cli.py
Here is a bug fix for a problem that affects Python 3. A `geojson` input file is read as binary through the CLI, and reading like `input_geojson.read()` then returns a `bytes` object which is not accepted by `json.loads()`. I guess this is just a simple typo.
I have tested the new code in Python 2.7.8 and Python 3.4.3.
Thanks for writing and sharing great software!
=> Treat geojson input in CLI as text, not binary

.travis.yml, CHANGELOG.txt, requirements.txt, src/rasterstats/cli.py, src/rasterstats/io.py, src/rasterstats/main.py, src/rasterstats/utils.py, tests/test_io.py, tests/test_utils.py, tests/test_zonal.py
This is a big shift, pulling all the coordinate transform and raster data access logic out of `zonal_stats` and into a `Raster` class. It allows for much cleaner and faster code all around and opens the door for alternate sources of array-like data (pytables, netcdf, hdf5, blaze, etc).
Currently requires rasterio master but after the rasterio 0.27 release, this will be good to go. 
Resolves #86 and #64
=> Raster refactor

CHANGELOG.txt, src/rasterstats/__init__.py, src/rasterstats/main.py, src/rasterstats/point.py, src/rasterstats/utils.py, tests/test_point.py
simpler function for point queries where aggregate zonal stats are not relevant, but sub-pixel interpolation methods are
Resolves #69 and #87
=> Point query

src/rasterstats/io.py
was: "returns col, row"
now: "returns row, col"
This now consistent with the existing implmentation and
the conventions for indexing arrays (in C-ish languages).
=> fix the Raster.index docstring

src/rasterstats/main.py, tests/test_zonal.py
I recently found it helpful to have a hook to run arbitrary functions on the rasterized zone array.  I added an optional kwarg to `zonal_stats` called `zone_funcs` which expects a list of callables to apply to zone ndarray prior to calculating stats.
=> add zone_funcs to zonal_stats

.gitignore, src/rasterstats/main.py, tests/test_cli.py, tests/test_io.py, tests/test_zonal.py
=> Test coverage

src/rasterstats/main.py
The existing code produced the following warning, this commit removes the warning.
```
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
```
=> Remove use of deprecated functionality

docs/manual.rst, requirements.txt, tests/test_io.py, tests/test_point.py, tests/test_zonal.py
The next version will require Rasterio 1.0.
This PR changes the code to use the `.transform` property instead of `.affine` on the Rasterio dataset object. 
Towards #155 - though we still use `affine` internally, all Rasterio usage is updated to use `transform`.
=> Require Rasterio 1.0

src/rasterstats/utils.py
The following line in the `boxify_points` utils function was creating a positive buffer value since the `min` of the cell size dimensions is already a negative number. This was resulting in a buffered pixel box that would overlap with surrounding cells when using `all_touched`.
`buff = -0.01 * min(rast.affine.a, rast.affine.e)`
=> Fix boxify_points to correctly use a negative buffer

.travis.yml, src/rasterstats/main.py
Fixes #183 
Added a version check for numpy that either calls a now-deprecated method or the current standard method for returning scalars when parsing information from multi-feature shapefiles. Deprecated calls are maintained for backwards compatibility.
=> Updated method calls for numpy v1.16

src/rasterstats/io.py
Dear maintainers of python-rasterstats,
I'm running Python 3.8 and get warnings about using the `collections` package directly for `Iterable` and `Mapping`. As suggested, they should be loaded from `collections.abc`.
Second, `rasterio` is deprecating "Right multiplication" so I fixed these two multiplications.
Let me know what you think.
=> Removing warnings from Python 3.8 installations

src/rasterstats/io.py, src/rasterstats/main.py, src/rasterstats/point.py, tests/test_io.py
1) There are use cases where features being outside the raster extent is an error. For example in my job I am provided with countrywide rasters and I collect statistics from these rasters for buildings and roads. If a feature is outside the raster extent something is wrong with either the feature or the raster.
2) Enabling boundless reading in rasterio seriously degrades performance in some cases. It looks like the dataset is opened for each feature and the block cache is effectively disabled when using boundless reading. This gist https://gist.github.com/AsgerPetersen/6f9c8120b85e462ccbc26191a2117b3a demonstrates a performance improvement about 50x when disabling boundless reading.
=> Allow toggling off boundless reading

src/rasterstats/io.py
If I pass a pre-loaded int array that's already pretty large, then it tends to have a memory error since the default for `np.empty` is float64. It seems reasonable to keep the dtype constant here.
=> set dtype in new array creation

docs/cli.rst, docs/index.rst, docs/manual.rst, src/rasterstats/cli.py
There are small typos in:
- docs/cli.rst
- docs/index.rst
- docs/manual.rst
- src/rasterstats/cli.py
Fixes:
- Should read `digital` rather than `digitial`.
- Should read `vertices` rather than `verticies`.
- Should read `statistics` rather than `statisics`.
- Should read `severely` rather than `severly`.
- Should read `occurrences` rather than `occurences`.
- Should read `intermediate` rather than `intemediate`.
- Should read `geometry` rather than `geometery`.
- Should read `dictionary` rather than `dictionnary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

pyproject.toml, scripts/release.sh, setup.py
This implements [PEP 518](https://peps.python.org/pep-0518/) by adding a `pyproject.toml` file with the build system requirements.
Also a few related things:
- Use `python -m build` to build sdist (.tar.gz) and wheel files
- Use `twine check --strict` to raise error on warnings, and...
- Add `long_description_content_type='text/x-rst'` to fix `twine check --strict`
=> PEP-518: specify minimum build system requirements with pyproject.toml

src/rasterstats/io.py, src/rasterstats/main.py, src/rasterstats/utils.py, tests/test_io.py, tests/test_zonal.py
This PR resolves a few shapely deprecation warnings:
- Use `shapely.errors.ShapelyError` (`ReadingError` was also only from `shapely.errors`)
- Use `geom.geom_type` instead of `geom.type`
- Fix inconsistent dimensionality error with test polygon
- Use [`pytest.importorskip`](https://docs.pytest.org/en/7.1.x/how-to/skipping.html#skipping-on-a-missing-import-dependency) feature
=> Resolve shapely deprecation warnings; use pytest.importorskip

src/rasterstats/io.py
The python warnings filter is buggy and does not respect the `once` action. This is particularly annoying for the nodata warnings as its called on every feature.
This PR implements a hack using a global bool to avoid repeat warnings.
Should clean up the logs for anyone who uses arrays directly as rasters.
=> Warn about Nodata only once

docs/conf.py, examples/benchmark.py, src/rasterstats/__init__.py, src/rasterstats/cli.py, src/rasterstats/io.py, src/rasterstats/main.py, src/rasterstats/point.py, src/rasterstats/utils.py, tests/myfunc.py, tests/test_cli.py, tests/test_io.py, tests/test_zonal.py
This was mostly automated using [pyupgrade](https://github.com/asottile/pyupgrade), which does several things mostly related to Python 2 to 3 upgrades:
- The default encoding for Python 3 is utf-8 ([PEP 3120](https://peps.python.org/pep-3120/)), so no need to specify this
- Remove old `from __future__` imports
- Use `yield from` statement ([PEP 380](https://peps.python.org/pep-0380/))
- Use `OSError` instead of the `IOError` alias ([PEP 3151](https://peps.python.org/pep-3151/))
- The default second argument to `open()` is `"r"`, so this is removed. This one could be controversial, but the contexts where this is done it is clear the file is being read.
The only manual edit is to rephrase an exception message in src/rasterstats/main.py
=> Python 3 upgrades

docs/conf.py, examples/benchmark.py, examples/multiproc.py, examples/simple.py, pyproject.toml, src/rasterstats/__init__.py, src/rasterstats/cli.py, src/rasterstats/io.py, src/rasterstats/main.py, src/rasterstats/point.py, src/rasterstats/utils.py, tests/test_cli.py, tests/test_io.py, tests/test_point.py, tests/test_utils.py, tests/test_zonal.py
This PR simplifies and tidies imports using [isort](https://pycqa.github.io/isort/) and [absolufy-imports](https://github.com/MarcoGorelli/absolufy-imports). Other unused imports are cleaned up, as well as a few manual edits related to imports.
This brings consistency of imports, and [PEP 8](https://peps.python.org/pep-0008/) recommends absolute imports (previously a mixture of relative and absolute were used).
=> Sort and absolufy imports

.github/workflows/test-rasterstats.yml, pyproject.toml, src/rasterstats/io.py, tests/test_io.py
This attempts to bring support for the latest release of Fiona, currently v1.9.2. Here are some notes:
- The upper version for Fiona is unpinned (xref #275)
- Also unpin the upper version for unreleased version of Affine (pinning should generally be avoided)
- The big change from Fiona 1.8 to 1.9 is that Features and Properties are not `dict`, but are MutableMapping class instances
- <s>Use ObjectEncoder from `fiona.model` with `json.dumps` (xref https://github.com/Toblerity/Fiona/issues/1229)</s>
- See also [RFC 1: Changes for Fiona 2.0](https://github.com/Toblerity/fiona-rfc/blob/master/rfc/0001-fiona-2-0-changes.md#considerations), which changes some Fiona object to immutable objects
Probably some more refinement might be needed to align to Fiona's development path, but this is a …
=> Provide compatibility with Fiona 1.9

src/rasterstats/main.py, tests/test_zonal.py
This PR is giving access to the `rv_array` within custom functions to build more advanced stats.
----
We are using zonal_stats within a project for the United Nations to calculate intersect areas and percentages. Because the nodata filter gets applied to the mask beforehand, we found it difficult to calculate the intersect percentage with custom functions. We resorted to calculating as a combination of metrics, see https://github.com/WFP-VAM/prism-app/pull/893. But it would be great to have access to the rv_array to give users a bit more flexibility to implement more complex statistics.
This is an attempt to do just that :)
PS - super grateful for your project @perrygeo !
=> Add rv_array to custom functions

.github/workflows/test-rasterstats.yml, pyproject.toml, src/rasterstats/main.py
To confirm latest python version is working and keep up with https://devguide.python.org/versions/ 
I removed the test for older dependency versions - they don't work on python 3.12. If our dependencies are not backported to keep up with Python releases, then its not feasible for us to do so.
=> ci: test against python 3.12, drop 3.7

pyproject.toml, src/rasterstats/main.py
- Added tqdm to main.py in zonal_stats function
- `stats` generator is created doing `gen_zonal_stats()` and then the total length of the generator (for `tqdm` to know) is done doing `total=sum(1 for _ in stats)`. Not sure how I feel about this.
- if `progress == True`, the `zonal_stats()` function will return the list comprehension using the `tqdm` module, if not it will return the original generator list-initialization.
- Added tqdm in project.optional-dependencies in pyproject.toml.
=> Addressing progress bar issue

.github/workflows/test-rasterstats.yml, pyproject.toml, src/rasterstats/io.py
Fiona behavior changed slightly when opening GeoJSON strings. See https://github.com/Toblerity/Fiona/issues/1455
We can work around this in a backwards compatible way by catching the `ValueError` so that GeoJSON strings take the `json.loads` code path.
=> Fix for fiona 1.10

pyproject.toml, pytest.ini, src/rasterstats/io.py, src/rasterstats/main.py, tests/test_cli.py, tests/test_io.py, tests/test_utils.py, tests/test_zonal.py
Attempts to use pathlike objects yields an unexpected errror:
```python
from pathlib import Path
polygons = Path(DATA) / "polygons.shp"
stats = zonal_stats(polygons, raster)
```
This PR allows pathlike vector sources.
Other changes:
- Rewrite tests to use `pathlib` (rather than `os.path`)
- Move `pytest.ini` to `pyproject.toml`, and use `testpaths = ["tests"]` instead of `norecursedirs`
=> Allow path-like objects for vector source; use Path for tests

.gitignore
currently experiencing too much churn in the uv lockfile, see https://github.com/astral-sh/uv/issues/10845
Until this is fixed, ie I can use `uv run` without updating my lockfile, I'm going to ignore it. Applications, not libraries, should arguably be setting their own locked dependency sets anyhow.
=> ignore the uv.lock file for now
